env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-plusplus: [2, { "allowForLoopAfterthoughts": true }]
  import/extensions: [0, {
  <js>: "always"
  }]
  import/prefer-default-export: off
  linebreak-style: [0, "windows"]



